function [] = wrtBModesSecFile(BModesSecFile,HtFrac,MassDenSecs,TwrFAStff, ...
                  TwrSSStff,TwrGJStff,TwrEAStff,TwrFAIner,TwrSSIner)
             
% fucntion: write Bmodes sectional property file
% Written by: Yang Yang in Ningbo University
% Date:     : 25th May 2021
% email: yangyang1@nbu.edu.cn

NumLines = length(MassDenSecs);

fid1 = fopen(BModesSecFile,'wt');

fprintf(fid1,'%s \n','Tower sectional properties generated by the code developed by Yang Yang');
fprintf(fid1,'%5d \t %s \n',NumLines,'n_secs:	number	of	tower	sections	at	which	properties	are	specified	(-)	');
fprintf(fid1,'%s \n',' ');
fprintf(fid1,'%s \n','sec_loc	str_tw	tw_iner	mass_den	flp_iner	edge_iner	flp_stff	edge_stff	tor_stff	axial_stff	cg_offst	sc_offst	tc_offst');
fprintf(fid1,'%s \n','(-)	(deg)	(deg)	(kg/m)	(kg-m)	(kg-m)	(Nm^2)	(Nm^2)	(Nm^2)	(N)	(m)	(m)	(m)');

formatOut = '%8.3f \t %2d \t %2d %13.6e \t';
for i=1:6
    formatOut = strcat(formatOut,'%13.6e \t');
end
formatOut = strcat(formatOut,32,'%2d \t %2d \t %2d \t \n');

for i=1:NumLines
    fprintf(fid1,formatOut,HtFrac(i),0,0,MassDenSecs(i),TwrFAIner(i),TwrSSIner(i),...
       TwrFAStff(i),TwrSSStff(i),TwrGJStff(i),TwrEAStff(i),0,0,0);
end
fprintf(fid1,'%s \n',' ');
fprintf(fid1,'%s \n',' ');
fprintf(fid1,'%s \n',' ');
fprintf(fid1,'%s \n','**Note: If the above data represents TOWER properties, the following are overwritten:');
fprintf(fid1,'%s \n','str_tw is set to zero');
fprintf(fid1,'%s \n','tw_iner is set to zero');
fprintf(fid1,'%s \n','cg_offst is set to zero');
fprintf(fid1,'%s \n','sc_offst is set to zero');
fprintf(fid1,'%s \n','tc_offst is set to zero');
fprintf(fid1,'%s \n','edge_iner is set equal to flp_iner');
fprintf(fid1,'%s \n','edge_stff is set equal to flp_stff');
fclose('all');  

  
