!  TransAQWA2FAST_QTF.f90 
!
!  FUNCTIONS:
!  TransAQWA2FAST_QTF - Entry point of console application.
!

!****************************************************************************
!
!  PROGRAM: TransAQWA2FAST_QTF
!
!  PURPOSE:  To transfer the QTF (Quadratic Transfer Functions) coefficients produced by AQWA to the format of WAMIT.
!
!****************************************************************************

    program TransAQWA2FAST_QTF

    implicit none


    integer,parameter :: UnAQ = 11          !- I/O for the AQWA input
    integer,parameter :: UnSF = 12        !- I/O for the hydrostatic stiffness file (.hst)
    integer,parameter :: UnDF = 13        !- I/O for the added mass and damping file (.1)
	
! Parameters	
	real,parameter :: PI = 3.1415926
	real,parameter :: R2D=180.0/PI
	
! Variables from the input	
	character(len=1204) ::  AQWAInputQTF	!- Filename of AQWA QTF including the suffix 
	real    :: GravAcce						! Gravity acceleration
	real    :: WaterDen						! Water density	! Time and date information that will be output in the result file.
    logical :: FlagCnvrtAll    				! Flag of one direction. True: convert all data within the file. False: only convert the data in one wave direction and then give the direction belowcharacter(len=8) :: Currdate
    real    :: TrgtWvDir					! Target wave directioncharacter(len=10) :: CurrTime
	
! Local variables	
	real,allocatable :: Hds(:),Freqs(:)
	real,allocatable ::QTF_Force_DRe(:,:,:,:)
	real,allocatable ::QTF_Force_SRe(:,:,:,:)
	real,allocatable ::QTF_Force_DIm(:,:,:,:)
	real,allocatable ::QTF_Force_SIm(:,:,:,:)
	integer :: NumStr,NumHds,NumFreqs,NumHdsLines,NumFreqsLines
	integer :: i,j,k,ii
	integer :: StrID,WvDirID,FreqID1,FreqID2
	integer :: trgtWvHdID                     ! Index of the target wave
	real    :: TempValues(6)
	real	:: QTF_SFMod
	real	:: QTF_SPhy
	real	:: QTF_DFMod
	real	:: QTF_DPhy
	character(len=1024) :: TempLine
	
	! Time and date information that will be output in the result file.
    character(len=8)  :: Currdate
    character(len=10) :: CurrTime
    character(len=50) :: Time_Date

	

! Body of TransAQWA2FAST_QTF

! Time and date of generating the current file.
   call date_and_time(DATE=Currdate,Time=CurrTime)
   Time_Date = 'at '//CurrTime(1:2)//':'//CurrTime(3:4)//':'//CurrTime(5:6)
   Time_Date = trim(Time_Date)//' on '//Currdate(7:8)//'-'//Currdate(5:6)//'-'//Currdate(1:4)		
	
! write the notice
	write (*,'(A)') '-----------------------------------------------------------------------------',&
                ' This code is developed by Dr Yang Yang from Ningbo University on 01-Aug-2021',&
                ' for converting Quadratic Transfer Functions of a floating platform to the',&
		        ' WAMIT format using the **.QTF file generated by AQWA for use in OpenFAST.',&
                '-----------------------------------------------------------------------------'
	 
	open (1, file = 'Input4TransAQWA2FAST_QTF.txt')
	 read (1,*) ! skip the comment
	 read (1,*) AQWAInputQTF		! Filename of AQWA QTF including the suffix 
	 read (1,*) GravAcce			! Gravity acceleration
	 read (1,*) WaterDen			! Water density	
	 read (1,*) FlagCnvrtAll    	! Flag of one direction. True: convert all data within the file. False: only convert the data in one wave direction and then give the direction below
	 if (.not. FlagCnvrtAll) then
        read (1,*) TrgtWvDir			! Target wave direction
	 endif
	close(1)
	
	
	
	open (UnAQ,file = trim(AQWAInputQTF))
	 write (*,*)
     write (*,*) ' Reading data from the file: '//trim(AQWAInputQTF) 
	 read(UnAQ,*) ! skip the comment
	 read (UnAQ,'(A1024)') TempLine
     read (TempLine(1:13),*) NumStr,NumHds,NumFreqs
! write a notice to the user
	 write(*,'(I4,A,I3,A)') NumHds,' wave headings and ',NumFreqs, ' frequencies included'
! allocate memory for matices
	 allocate (Hds(NumHds))
	 allocate (Freqs(NumFreqs))
	 allocate (QTF_Force_DRe(NumFreqs,NumFreqs,NumHds,6)) 
	 allocate (QTF_Force_DIm(NumFreqs,NumFreqs,NumHds,6)) 
	 allocate (QTF_Force_SRe(NumFreqs,NumFreqs,NumHds,6)) 
	 allocate (QTF_Force_SIm(NumFreqs,NumFreqs,NumHds,6)) 
! re-assign the line
	 TempLine = TempLine(17:1024)
	 if (NumHds<=6) then
       read (TempLine,*) (Hds(i),i=1,NumHds)
     else
        NumHdsLines = floor(NumHds/6.0)
        if (NumHdsLines<3) then
           read (TempLine,*) (Hds(i),i=1,6)
           read (UnAQ,*) (Hds(i),i=7,NumHds)
        else
           read (TempLine,*) (Hds(i),i=1,6)
           do i=1,NumHdsLines-1
              read (UnAQ,*) (Hds(j),j=i*6+1,i*6+6)
           enddo
           if ((NumHds - 6*NumHdsLines) > 0) then
              read (UnAQ,*) (Hds(j),j=NumHdsLines*6+1,NumHds)
           endif
        endif
     endif
     
     if (NumFreqs < 7 ) then
        read (UnAQ,*) (Freqs(j),j=1,NumFreqs)
     else
        NumFreqsLines = floor(NumFreqs/6.0)
        do i=1, NumFreqsLines
           read (UnAQ,*) (Freqs(j),j=(i-1)*6+1,i*6)
        enddo
        if ((NumFreqs - 6*NumFreqsLines) > 0) then
              read (UnAQ,*) (Freqs(j),j=NumFreqsLines*6+1,NumFreqs)
        endif
	 endif
 
! read the data into the matrice  QTF_Force	 
	 do i=1,NumFreqs
		 do j=1,NumFreqs
			do k=1,NumHds
			   read (UnAQ,'(A1024)') TempLine
			   read (TempLine,*) StrID,WvDirID,FreqID1,FreqID2,(TempValues(ii),ii=1,6)
			   QTF_Force_DRe(FreqID1,FreqID2,WvDirID,:) = TempValues
			   read(UnAQ,*) (QTF_Force_DIm(FreqID1,FreqID2,WvDirID,ii),ii=1,6)
			   read(UnAQ,*) (QTF_Force_SRe(FreqID1,FreqID2,WvDirID,ii),ii=1,6)
			   read(UnAQ,*) (QTF_Force_SIm(FreqID1,FreqID2,WvDirID,ii),ii=1,6)
			enddo ! wave headings
		 enddo    ! Frequency 1
	 enddo        ! Frequency 2
! done reading and correct the force to coefficient 
	QTF_Force_DRe = QTF_Force_DRe/(WaterDen*GravAcce) 
	QTF_Force_DIm = QTF_Force_DIm/(WaterDen*GravAcce) 
	QTF_Force_SRe = QTF_Force_SRe/(WaterDen*GravAcce) 
	QTF_Force_SIm = QTF_Force_SIm/(WaterDen*GravAcce) 
! open files to store the QTF coefficients
	 open (UnSF,file = AQWAInputQTF(1:len(trim(AQWAInputQTF))-4)//'.12s' )
	  write(UnSF,'(A)') 'QTF Sum coefficients converted from the AQWA output ('//trim(AQWAInputQTF)//') using the code written by Dr Yang Yang based in Ningbo University '//trim(Time_Date)
	  
	 open (UnDF,file = AQWAInputQTF(1:len(trim(AQWAInputQTF))-4)//'.12d' )
	  write(UnDF,'(A)') 'QTF Difference coefficients converted from the AQWA output ('//trim(AQWAInputQTF)//') using the code written by Dr Yang Yang based in Ningbo University '//trim(Time_Date)
	 
! write the data to the files
	 write (*,*) 
	 write (*,*) ' Writing the data ...'
	 write (*,*) 
	 if (FlagCnvrtAll) then  ! Output all directions
		 do i=1,NumFreqs
			 do j=1,NumFreqs
				 do k=1,NumHds
					 do ii=1,6
						 QTF_SFMod = sqrt(QTF_Force_SIm(i,j,k,ii)**2 + QTF_Force_SRe(i,j,k,ii)**2)
						 QTF_SPhy  = asin(QTF_Force_SIm(i,j,k,ii)/QTF_SFMod)*R2D
						 QTF_DFMod = sqrt(QTF_Force_DIm(i,j,k,ii)**2 + QTF_Force_DRe(i,j,k,ii)**2)
						 QTF_DPhy  = asin(QTF_Force_DIm(i,j,k,ii)/QTF_DFMod)*R2D
						 write(UnSF,'(4(ES15.7),I5,4(ES15.7))') 2.0*PI/Freqs(i),2.0*PI/Freqs(j),Hds(k),Hds(k),ii,QTF_SFMod,QTF_SPhy,QTF_Force_SRe(i,j,k,ii),QTF_Force_SIm(i,j,k,ii)
						 write(UnDF,'(4(ES15.7),I5,4(ES15.7))') 2.0*PI/Freqs(i),2.0*PI/Freqs(j),Hds(k),Hds(k),ii,QTF_DFMod,QTF_DPhy,QTF_Force_DRe(i,j,k,ii),QTF_Force_DIm(i,j,k,ii)
					 enddo ! force direction
				 enddo	! frequency 1
			 enddo	! frequency 2
		 enddo ! wave headings
	 else                    ! Output the specified direction only
		 do k=1,NumHds
			 if (abs(TrgtWvDir-Hds(k)) < 1.0e-6) then
				 trgtWvHdID = k
			 endif
		 enddo
		 do i=1,NumFreqs
			 do j=1,NumFreqs
				 do ii=1,6
					 QTF_SFMod = sqrt(QTF_Force_SIm(i,j,trgtWvHdID,ii)**2 + QTF_Force_SRe(i,j,trgtWvHdID,ii)**2)
					 QTF_SPhy  = asin(QTF_Force_SIm(i,j,trgtWvHdID,ii)/QTF_SFMod)*R2D
					 QTF_DFMod = sqrt(QTF_Force_DIm(i,j,trgtWvHdID,ii)**2 + QTF_Force_DRe(i,j,trgtWvHdID,ii)**2)
					 QTF_DPhy  = asin(QTF_Force_DIm(i,j,trgtWvHdID,ii)/QTF_DFMod)*R2D
					 write(UnSF,'(4(ES15.7),I5,4(ES15.7))') 2.0*PI/Freqs(i),2.0*PI/Freqs(j),Hds(trgtWvHdID),Hds(trgtWvHdID),ii,QTF_SFMod,QTF_SPhy,QTF_Force_SRe(i,j,trgtWvHdID,ii),QTF_Force_SIm(i,j,trgtWvHdID,ii)
					 write(UnDF,'(4(ES15.7),I5,4(ES15.7))') 2.0*PI/Freqs(i),2.0*PI/Freqs(j),Hds(trgtWvHdID),Hds(trgtWvHdID),ii,QTF_DFMod,QTF_DPhy,QTF_Force_DRe(i,j,trgtWvHdID,ii),QTF_Force_DIm(i,j,trgtWvHdID,ii)
				 enddo ! force direction
			 enddo	! frequency 1
		 enddo	! frequency 2
		 
	 endif
	 close(UnSF)
	 close(UnDF)
	 
     ! All done
    write (*,*) 
    write (*,'(A)') '  All Done!'
    write (*,'(A)')  ' Please check the files: '
    write (*,'(A)') '  1: '//AQWAInputQTF(1:len(trim(AQWAInputQTF))-4)//'.12s'
	write (*,'(A)') '  2: '//AQWAInputQTF(1:len(trim(AQWAInputQTF))-4)//'.12d'	 
	write (*,*) 
	 
	 
    end program TransAQWA2FAST_QTF

